 backend:
    name: git-gateway
    branch: main

  site_url: https://ehab-guitarrista-netlify-v1.vercel.app
  display_url: https://ehab-guitarrista-netlify-v1.vercel.app

  media_folder: "public/lovable-uploads"
  public_folder: "/lovable-uploads"

collections:
  - name: "site-content"
    label: "Site Content"
    files:
      - file: "src/data/content.json"
        label: "Main Content"
        name: "content"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - label: "Main Title"
                name: "title"
                widget: "string"
                default: "Ehab Guitarrista"
              - label: "Subtitle"
                name: "subtitle"
                widget: "string"
                default: "Bringing Music to Life Across Canada"
